-- 
-- Please see the license.txt file included with this distribution for 
-- attribution and copyright information.
--

-- NPC range properties
-- [weapon name] = {range increment, maximumm range increments}
weaponranges = {
	["blowgun"] = {20, 10},
	["bolas"] = {10, 5},
	["bola"] = {10, 5},
	["club"] = {10, 5},
	["composite longbow"] = {110, 10},
	["composite shortbow"] = {70, 10},
	["dagger"] = {10, 5},
	["dart"] = {20, 5},
	["halfling sling staff"] = {80, 10},
	["hand crossbow"] = {30, 10},
	["heavy crossbow"] = {120, 10},
	["javelin"] = {30, 5},
	["light crossbow"] = {80, 10},
	["light hammer"] = {20, 5},
	["longbow"] = {100, 10},
	["net"] = {10, 1},
	["repeating heavy crossbow"] = {120, 10},
	["repeating light crossbow"] = {80, 10},
	["shortbow"] = {60, 10},
	["shortspear"] = {20, 5},
	["shuriken"] = {10, 5},
	["sling"] = {50, 10},
	["spear"] = {20, 5},
	["starknife"] = {20, 5},
	["throwinig axe"] = {10, 5},
	["trident"] = {10, 5},
	
	["brass knife"] = {10, 5},
	["kunai"] = {10, 5},
	["wooden stake"] = {10, 5},
	["spring blade"] = {10, 5},
	["stingchuck"] = {10, 5},
	["dueling dagger"] = {10, 5},
	["switchblade knife"] = {10, 5},
	["syringe spear"] = {20, 5},
	["ammentum"] = {50, 5},
	["chakram"] = {30, 5},
	["jolting dart"] = {20, 5},
	["hunga munga"] = {15, 5},
	["hurlbat"] = {10, 5},
	["pilum"] = {20, 5},
	["throwing arrow cord"] = {60, 10},
	["aklys"] = {20, 5},
	["flying talon"] = {10, 5},
	["stonebow"] = {50, 10},
	["deer horn knife"] = {20, 5},
	["dwarven maulaxe"] = {10, 5},
	["knobkerrie"] = {20, 5},
	["dwarven ram hammer"] = {10, 5},
	["chain-hammer"] = {20, 5},
	["harpoon"] = {10, 5},
	["totem spear"] = {10, 5},
	["dwarven sphinx hammer"] = {20, 5},
	["brutal bola"] = {10, 5},
	["boomerang"] = {30, 5},
	["thorn bow"] = {40, 10},
	["flask thrower"] = {20, 10},
	["grappling hook"] = {10, 5},
	["orc hornbow"] = {80, 10},
	["stormshaft javalin"] = {30, 5},
	["snag net"] = {10, 1},
	["throwing shield"] = {20, 5},
	["shrillshaft javalin"] = {30, 5},
	["double sling"] = {50, 10},
	["glove sling"] = {50, 10},
	["wrist launcher"] = {20, 10},
	["heavy wrist launcher"] = {30, 10},
	
	--Firearms are in this section. I have max touch attack as the max range increment instead of the actual max range increment, which is 5 range increments for early firearms and 10 for modern.
	--Early firearms
	["breech-loader"] = {20, 1},
	["buckler gun"] = {10, 1},
	["pepperbox"] = {20, 1},
	["pistol"] = {20, 1},
	["coat pistol"] = {10, 1},
	["dagger pistol"] = {10, 1},
	["double-barreled pistol"] = {20, 1},
	["dragon pistol"] = {20, 1},
	["dragoon pistol"] = {30, 1},
	["paddle-foot pistol"] = {20, 1},
	["sword cane pistol"] = {10, 1},
	["air repeater"] = {50, 1},
	["blunderbuss"] = {10, 1},
	["culverin"] = {30, 1},
	["cylinder rifle"] = {40, 1},
	["double hackbut"] = {50, 1},
	["fire lance"] = {10, 1},
	["musket"] = {40, 1},
	["axe musket"] = {30, 1},
	["double-barreled musket"] = {40, 1},
	["dragoon musket"] = {60, 1},
	["warhammer musket"] = {30, 1},
	-- Modern firearms are in this section
	["revolver"] = {20, 5},
	["rifle"] = {80, 5},
	["pepperbox rifle"] = {80, 5},
	["shotgun"] = {20, 5},
	["double-barreled shotgun"] = {20, 5}
};
